'use strict';
const vscode=require('vscode');
const path=require('path');
const core=require('./src');

function workspaceRoot(){const editor=vscode.window.activeTextEditor;const folder=editor&&vscode.workspace.getWorkspaceFolder(editor.document.uri);return folder?.uri.fsPath||vscode.workspace.workspaceFolders?.[0]?.uri.fsPath||null;}
function settings(){const c=vscode.workspace.getConfiguration('cortex');return{
 checkpointIntervalMinutes:Number(c.get('checkpointIntervalMinutes',5)),eventCheckpointDebounceSeconds:Number(c.get('eventCheckpointDebounceSeconds',30)),foreignOrchestratorPolicy:c.get('foreignOrchestratorPolicy','block'),autoInstallTrustedSkills:Boolean(c.get('autoInstallTrustedSkills',true)),skillScope:c.get('skillScope','ide-global'),runSecurityAfterVerify:Boolean(c.get('runSecurityAfterVerify',true)),allowExternalSecurityTools:Boolean(c.get('allowExternalSecurityTools',false)),maxCheckpointHistory:Number(c.get('maxCheckpointHistory',200))};}
async function activate(context){
 const output=vscode.window.createOutputChannel('Cortex');context.subscriptions.push(output);
 const status=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left,20);status.command='cortex.status';context.subscriptions.push(status);
 let timer=null,eventTimer=null;
 const updateStatus=()=>{const w=workspaceRoot();if(!w){status.hide();return;}const s=core.isolationStatus(w);status.text=s.enabled?`$(brain) Cortex ${s.marker?.mode==='observer'?'Observer':'On'}`:'$(circle-slash) Cortex Off';status.tooltip=s.dockyardRepo?'DockyardOS owns this workspace':s.foreign.length?`Foreign orchestrator: ${s.foreign.join(', ')}`:'Cortex workspace orchestrator';status.show();};
 const safeCheckpoint=(reason,extra={})=>{const w=workspaceRoot();if(!w)return;try{if(core.canExecute(w).ok)core.createCheckpoint(w,reason,extra,{maxHistory:settings().maxCheckpointHistory});}catch(e){output.appendLine(`Checkpoint skipped: ${e.message}`);}};
 const scheduleEventCheckpoint=(reason)=>{if(eventTimer)clearTimeout(eventTimer);eventTimer=setTimeout(()=>safeCheckpoint(reason),Math.max(5,settings().eventCheckpointDebounceSeconds)*1000);};
 const resetTimer=()=>{if(timer)clearInterval(timer);timer=setInterval(()=>safeCheckpoint('interval'),Math.max(1,settings().checkpointIntervalMinutes)*60*1000);};resetTimer();
 context.subscriptions.push({dispose(){if(timer)clearInterval(timer);if(eventTimer)clearTimeout(eventTimer);}});
 context.subscriptions.push(vscode.workspace.onDidSaveTextDocument(()=>scheduleEventCheckpoint('editor-save')),vscode.workspace.onDidCreateFiles(()=>scheduleEventCheckpoint('files-created')),vscode.workspace.onDidDeleteFiles(()=>scheduleEventCheckpoint('files-deleted')),vscode.workspace.onDidRenameFiles(()=>scheduleEventCheckpoint('files-renamed')),vscode.workspace.onDidChangeConfiguration(e=>{if(e.affectsConfiguration('cortex'))resetTimer();updateStatus();}),vscode.workspace.onDidChangeWorkspaceFolders(updateStatus));
 const cmd=(name,fn)=>context.subscriptions.push(vscode.commands.registerCommand(name,fn));
 cmd('cortex.enableWorkspace',async()=>{const w=workspaceRoot();if(!w)return vscode.window.showErrorMessage('Open a workspace first.');try{const s=settings();const marker=core.enableWorkspace({workspace:w,extensionRoot:context.extensionPath,foreignPolicy:s.foreignOrchestratorPolicy});if(marker.mode==='primary'){core.createCheckpoint(w,'cortex-enabled',{nextAction:'Inspect the current project and resume from the first unfinished task.'},{maxHistory:s.maxCheckpointHistory});core.generateResumeCapsule(w);}updateStatus();vscode.window.showInformationMessage(`Cortex enabled in ${marker.mode} mode.`);}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.disableWorkspace',()=>{const w=workspaceRoot();if(!w)return;core.disableWorkspace(w);updateStatus();vscode.window.showInformationMessage('Cortex disabled for this workspace.');});
 cmd('cortex.checkpoint',()=>{const w=workspaceRoot();if(!w)return;try{core.createCheckpoint(w,'manual',{}, {maxHistory:settings().maxCheckpointHistory});core.generateResumeCapsule(w);vscode.window.showInformationMessage('Cortex checkpoint saved.');}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.resume',async()=>{const w=workspaceRoot();if(!w)return;try{const cap=core.generateResumeCapsule(w);const doc=await vscode.workspace.openTextDocument(vscode.Uri.file(cap.file));await vscode.window.showTextDocument(doc,{preview:false});vscode.window.showInformationMessage(cap.state.reconciliation.stale?`Recovered newer repository state: ${cap.state.reconciliation.reasons.join(', ')}`:'Resume capsule refreshed.');}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.status',()=>{const w=workspaceRoot();if(!w)return;const s=core.isolationStatus(w);vscode.window.showInformationMessage(`Cortex ${s.enabled?'enabled':'disabled'} | mode ${s.marker?.mode||'-'} | foreign ${s.foreign.join(', ')||'none'} | DockyardOS repo ${s.dockyardRepo?'yes':'no'}`);});
 cmd('cortex.doctor',async()=>{const w=workspaceRoot();if(!w)return;output.show(true);output.appendLine('Running Cortex doctor...');const r=await core.doctor(w);output.appendLine(JSON.stringify(r,null,2));vscode.window.showInformationMessage(r.ready?'Cortex doctor passed.':'Cortex doctor found items needing attention. See output.');});
 cmd('cortex.routeTask',async()=>{const w=workspaceRoot();if(!w)return;const task=await vscode.window.showInputBox({prompt:'Describe the task Cortex should route'});if(!task)return;const route=core.routeTask(task);output.show(true);output.appendLine(`Route: ${JSON.stringify(route,null,2)}`);let ensured=[];const s=settings();if(s.autoInstallTrustedSkills&&route.externalSkills.length){await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: installing required trusted skills',cancellable:false},async()=>{ensured=await core.ensureSkills({extensionRoot:context.extensionPath,ids:route.externalSkills,scope:s.skillScope});});output.appendLine(`Skills: ${JSON.stringify(ensured,null,2)}`);}core.recordMemory(w,'routes',{task,route,ensured});safeCheckpoint('task-routed',{task,route,nextAction:'Follow the routed workflow and verify completion.'});vscode.window.showInformationMessage(`Cortex routed task: ${route.mode}.`);});
 cmd('cortex.ensureSkills',async()=>{const c=core.loadSkillCatalog(context.extensionPath);const picks=await vscode.window.showQuickPick(c.skills.map(s=>({label:s.id,description:s.description,id:s.id})),{canPickMany:true,placeHolder:'Select allow-listed skills to install globally'});if(!picks?.length)return;const r=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: installing trusted skills',cancellable:false},()=>core.ensureSkills({extensionRoot:context.extensionPath,ids:picks.map(x=>x.id),scope:settings().skillScope}));output.show(true);output.appendLine(JSON.stringify(r,null,2));const failed=r.filter(x=>x.status==='failed');vscode.window.showInformationMessage(failed.length?`${r.length-failed.length}/${r.length} skills installed/present; see output for failures.`:`${r.length} skills installed/present.`);});
 cmd('cortex.verifyWorkspace',async()=>{const w=workspaceRoot();if(!w)return;try{const report=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: deterministic verification',cancellable:false},()=>core.runVerification(w));output.show(true);output.appendLine(JSON.stringify(report,null,2));if(settings().runSecurityAfterVerify)await core.runSecurityAudit(w,{allowExternal:settings().allowExternalSecurityTools});safeCheckpoint('verification',{verificationStatus:report.status,nextAction:report.status==='pass'?'Continue with the next unfinished task.':'Repair verification failures before new work.'});vscode.window.showInformationMessage(`Cortex verification: ${report.status}.`);}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.securityAudit',async()=>{const w=workspaceRoot();if(!w)return;try{const r=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: security audit',cancellable:false},()=>core.runSecurityAudit(w,{allowExternal:settings().allowExternalSecurityTools}));output.show(true);output.appendLine(JSON.stringify(r,null,2));safeCheckpoint('security-audit',{securityStatus:r.status});vscode.window.showInformationMessage(`Cortex security audit: ${r.status}.`);}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.configureInspo',async()=>{const w=workspaceRoot();if(!w)return;const choice=await vscode.window.showQuickPick(['Enable Inspo MCP','Disable Inspo MCP']);if(!choice)return;try{const r=core.setInspo(w,choice.startsWith('Enable'));vscode.window.showInformationMessage(`Inspo MCP ${r.disabled?'disabled':'enabled'} for Cortex plugin. Reload Antigravity customizations if needed.`);}catch(e){vscode.window.showErrorMessage(e.message);}});
 updateStatus();
}
function deactivate(){}
module.exports={activate,deactivate};
