'use strict';
const vscode=require('vscode');
const core=require('./src');

function workspaceRoot(){const editor=vscode.window.activeTextEditor;const folder=editor&&vscode.workspace.getWorkspaceFolder(editor.document.uri);return folder?.uri.fsPath||vscode.workspace.workspaceFolders?.[0]?.uri.fsPath||null;}
function settings(){const c=vscode.workspace.getConfiguration('cortex');return{
 checkpointIntervalMinutes:Number(c.get('checkpointIntervalMinutes',5)),eventCheckpointDebounceSeconds:Number(c.get('eventCheckpointDebounceSeconds',30)),foreignOrchestratorPolicy:c.get('foreignOrchestratorPolicy','block'),autoInstallTrustedSkills:Boolean(c.get('autoInstallTrustedSkills',true)),skillScope:c.get('skillScope','ide-global'),runSecurityAfterVerify:Boolean(c.get('runSecurityAfterVerify',true)),allowExternalSecurityTools:Boolean(c.get('allowExternalSecurityTools',false)),maxCheckpointHistory:Number(c.get('maxCheckpointHistory',200))};}
async function activate(context){
 const output=vscode.window.createOutputChannel('Cortex');context.subscriptions.push(output);
 const status=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left,20);context.subscriptions.push(status);
 const prompted=new Set();let timer=null,eventTimer=null;
 const updateStatus=()=>{const w=workspaceRoot();if(!w){status.hide();return;}const init=core.initializationStatus(w),s=init.isolation;if(s.dockyardRepo){status.text='$(circle-slash) Cortex: DockyardOS';status.command='cortex.status';status.tooltip='DockyardOS owns this workspace. Cortex will not initialize here.';}else if(s.marker?.mode==='observer'){status.text='$(eye) Cortex Observer';status.command='cortex.status';status.tooltip='Cortex is read-only because another orchestrator owns this workspace.';}else if(!init.initialized){status.text='$(rocket) Initialize Cortex';status.command='cortex.initializeWorkspace';status.tooltip='One click: install trusted skills, configure Cortex, verify the project, and create recovery state.';}else if(init.health!=='ready'){status.text='$(warning) Repair Cortex';status.command='cortex.initializeWorkspace';status.tooltip='Cortex is initialized but setup has warnings. Click to retry missing setup.';}else{status.text='$(brain) Cortex Ready';status.command='cortex.status';status.tooltip='Cortex is initialized for this project.';}status.show();};
 const safeCheckpoint=(reason,extra={})=>{const w=workspaceRoot();if(!w)return;try{if(core.canExecute(w).ok)core.createCheckpoint(w,reason,extra,{maxHistory:settings().maxCheckpointHistory});}catch(e){output.appendLine(`Checkpoint skipped: ${e.message}`);}};
 const scheduleEventCheckpoint=(reason)=>{if(eventTimer)clearTimeout(eventTimer);eventTimer=setTimeout(()=>safeCheckpoint(reason),Math.max(5,settings().eventCheckpointDebounceSeconds)*1000);};
 const resetTimer=()=>{if(timer)clearInterval(timer);timer=setInterval(()=>safeCheckpoint('interval'),Math.max(1,settings().checkpointIntervalMinutes)*60*1000);};resetTimer();
 context.subscriptions.push({dispose(){if(timer)clearInterval(timer);if(eventTimer)clearTimeout(eventTimer);}});
 context.subscriptions.push(vscode.workspace.onDidSaveTextDocument(()=>scheduleEventCheckpoint('editor-save')),vscode.workspace.onDidCreateFiles(()=>scheduleEventCheckpoint('files-created')),vscode.workspace.onDidDeleteFiles(()=>scheduleEventCheckpoint('files-deleted')),vscode.workspace.onDidRenameFiles(()=>scheduleEventCheckpoint('files-renamed')),vscode.workspace.onDidChangeConfiguration(e=>{if(e.affectsConfiguration('cortex'))resetTimer();updateStatus();}),vscode.workspace.onDidChangeWorkspaceFolders(()=>{updateStatus();setTimeout(()=>offerInitialize(),400);}));
 const cmd=(name,fn)=>context.subscriptions.push(vscode.commands.registerCommand(name,fn));
 const initialize=async()=>{const w=workspaceRoot();if(!w)return vscode.window.showErrorMessage('Open a project folder first.');const s=settings(),before=core.initializationStatus(w);if(before.isolation.dockyardRepo)return vscode.window.showWarningMessage('Cortex will not initialize inside DockyardOS. DockyardOS remains the sole orchestrator for this workspace.');try{output.show(true);const result=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:before.initialized?'Cortex: repairing project setup':'Cortex: initializing project',cancellable:false},progress=>core.initializeProject({workspace:w,extensionRoot:context.extensionPath,extensionVersion:context.extension.packageJSON.version,foreignPolicy:s.foreignOrchestratorPolicy,skillScope:s.skillScope,installSkills:s.autoInstallTrustedSkills,verify:true,security:s.runSecurityAfterVerify,allowExternalSecurity:s.allowExternalSecurityTools,maxCheckpointHistory:s.maxCheckpointHistory,force:before.initialized&&before.health!=='ready',onProgress:p=>progress.report(p)}));output.appendLine(`Initialization: ${JSON.stringify(result,null,2)}`);updateStatus();if(result.mode==='observer')vscode.window.showWarningMessage('Cortex initialized in observer mode because another orchestrator owns this workspace.');else if(result.alreadyInitialized)vscode.window.showInformationMessage('Cortex is already initialized and ready for this project.');else if(result.health==='ready')vscode.window.showInformationMessage('Cortex is ready. Skills, recovery, verification, and project initialization are complete.');else vscode.window.showWarningMessage('Cortex initialized with warnings. Click “Repair Cortex” in the status bar after reviewing the Cortex output.');}catch(e){output.appendLine(`Initialization failed: ${e.stack||e.message}`);updateStatus();vscode.window.showErrorMessage(`Cortex initialization failed: ${e.message}`);}};
 cmd('cortex.initializeWorkspace',initialize);
 cmd('cortex.enableWorkspace',initialize);
 cmd('cortex.disableWorkspace',()=>{const w=workspaceRoot();if(!w)return;core.disableWorkspace(w);updateStatus();vscode.window.showInformationMessage('Cortex disabled for this workspace.');});
 cmd('cortex.checkpoint',()=>{const w=workspaceRoot();if(!w)return;try{core.createCheckpoint(w,'manual',{}, {maxHistory:settings().maxCheckpointHistory});core.generateResumeCapsule(w);vscode.window.showInformationMessage('Cortex checkpoint saved.');}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.resume',async()=>{const w=workspaceRoot();if(!w)return;try{const cap=core.generateResumeCapsule(w);const doc=await vscode.workspace.openTextDocument(vscode.Uri.file(cap.file));await vscode.window.showTextDocument(doc,{preview:false});vscode.window.showInformationMessage(cap.state.reconciliation.stale?`Recovered newer repository state: ${cap.state.reconciliation.reasons.join(', ')}`:'Resume capsule refreshed.');}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.status',()=>{const w=workspaceRoot();if(!w)return;const i=core.initializationStatus(w),s=i.isolation;vscode.window.showInformationMessage(`Cortex ${i.initialized?'initialized':'not initialized'} | health ${i.health||'-'} | mode ${s.marker?.mode||'-'} | foreign ${s.foreign.join(', ')||'none'} | DockyardOS repo ${s.dockyardRepo?'yes':'no'}`);});
 cmd('cortex.doctor',async()=>{const w=workspaceRoot();if(!w)return;output.show(true);output.appendLine('Running Cortex doctor...');const r=await core.doctor(w);output.appendLine(JSON.stringify(r,null,2));vscode.window.showInformationMessage(r.ready?'Cortex doctor passed.':'Cortex doctor found items needing attention. See output.');});
 cmd('cortex.routeTask',async()=>{const w=workspaceRoot();if(!w)return;const task=await vscode.window.showInputBox({prompt:'Describe the task Cortex should route'});if(!task)return;const route=core.routeTask(task);output.show(true);output.appendLine(`Route: ${JSON.stringify(route,null,2)}`);let ensured=[];const s=settings();if(s.autoInstallTrustedSkills&&route.externalSkills.length){await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: ensuring required trusted skills',cancellable:false},async()=>{ensured=await core.ensureSkills({extensionRoot:context.extensionPath,ids:route.externalSkills,scope:s.skillScope});});output.appendLine(`Skills: ${JSON.stringify(ensured,null,2)}`);}core.recordMemory(w,'routes',{task,route,ensured});safeCheckpoint('task-routed',{task,route,nextAction:'Follow the routed workflow and verify completion.'});vscode.window.showInformationMessage(`Cortex routed task: ${route.mode}.`);});
 cmd('cortex.ensureSkills',async()=>{const c=core.loadSkillCatalog(context.extensionPath);const picks=await vscode.window.showQuickPick(c.skills.map(s=>({label:s.id,description:s.description,id:s.id})),{canPickMany:true,placeHolder:'Select allow-listed skills to install globally'});if(!picks?.length)return;const r=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: installing trusted skills',cancellable:false},()=>core.ensureSkills({extensionRoot:context.extensionPath,ids:picks.map(x=>x.id),scope:settings().skillScope}));output.show(true);output.appendLine(JSON.stringify(r,null,2));const failed=r.filter(x=>x.status==='failed');vscode.window.showInformationMessage(failed.length?`${r.length-failed.length}/${r.length} skills installed/present; see output for failures.`:`${r.length} skills installed/present.`);});
 cmd('cortex.verifyWorkspace',async()=>{const w=workspaceRoot();if(!w)return;try{const report=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: deterministic verification',cancellable:false},()=>core.runVerification(w));output.show(true);output.appendLine(JSON.stringify(report,null,2));if(settings().runSecurityAfterVerify)await core.runSecurityAudit(w,{allowExternal:settings().allowExternalSecurityTools});safeCheckpoint('verification',{verificationStatus:report.status,nextAction:report.status==='pass'?'Continue with the next unfinished task.':'Repair verification failures before new work.'});vscode.window.showInformationMessage(`Cortex verification: ${report.status}.`);}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.securityAudit',async()=>{const w=workspaceRoot();if(!w)return;try{const r=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Cortex: security audit',cancellable:false},()=>core.runSecurityAudit(w,{allowExternal:settings().allowExternalSecurityTools}));output.show(true);output.appendLine(JSON.stringify(r,null,2));safeCheckpoint('security-audit',{securityStatus:r.status});vscode.window.showInformationMessage(`Cortex security audit: ${r.status}.`);}catch(e){vscode.window.showErrorMessage(e.message);}});
 cmd('cortex.configureInspo',async()=>{const w=workspaceRoot();if(!w)return;const choice=await vscode.window.showQuickPick(['Enable Inspo MCP','Disable Inspo MCP']);if(!choice)return;try{const r=core.setInspo(w,choice.startsWith('Enable'));vscode.window.showInformationMessage(`Inspo MCP ${r.disabled?'disabled':'enabled'} for Cortex plugin. Reload Antigravity customizations if needed.`);}catch(e){vscode.window.showErrorMessage(e.message);}});
 async function offerInitialize(){const w=workspaceRoot();if(!w||prompted.has(w))return;prompted.add(w);const i=core.initializationStatus(w),s=i.isolation;if(i.initialized||s.dockyardRepo||(s.foreign.length&&settings().foreignOrchestratorPolicy==='block'))return;const choice=await vscode.window.showInformationMessage('Cortex is installed but this project is not initialized yet. One click can set up skills, recovery, verification, and project memory.','Initialize Cortex');if(choice==='Initialize Cortex')await vscode.commands.executeCommand('cortex.initializeWorkspace');}
 updateStatus();setTimeout(()=>offerInitialize(),700);
}
function deactivate(){}
module.exports={activate,deactivate};
