'use strict';
const fs=require('fs');const path=require('path');const os=require('os');const crypto=require('crypto');const childProcess=require('child_process');
const mode=process.argv[2]||'';
function readStdin(){return new Promise(resolve=>{let s='';process.stdin.setEncoding('utf8');process.stdin.on('data',d=>s+=d);process.stdin.on('end',()=>{try{resolve(JSON.parse(s||'{}'));}catch{resolve({});}});});}
function output(v){process.stdout.write(`${JSON.stringify(v||{})}\n`);}
function readJson(f,x=null){try{return JSON.parse(fs.readFileSync(f,'utf8'));}catch{return x;}}
function ensureDir(d){fs.mkdirSync(d,{recursive:true});return d;}
function atomicJson(f,v){ensureDir(path.dirname(f));const t=`${f}.${process.pid}.${Date.now()}.tmp`;fs.writeFileSync(t,`${JSON.stringify(v,null,2)}\n`,{mode:0o600});fs.renameSync(t,f);}
function git(w,args){try{return childProcess.execFileSync('git',['-C',w,...args],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch{return '';}}
function canonical(p){try{return fs.realpathSync(p);}catch{return path.resolve(p);}}
function sanitizeRemote(r){r=String(r||'').trim();if(!r)return null;if(/^[^@\s]+@[^:]+:.+/.test(r))return r.replace(/^[^@]+@/,'git@');try{const u=new URL(r);u.username='';u.password='';u.search='';u.hash='';return u.toString().replace(/\/$/,'');}catch{return r.replace(/https?:\/\/[^/@]+@/,'https://');}}
function identity(w){const top=git(w,['rev-parse','--show-toplevel'])||canonical(w);const root=canonical(top),remote=sanitizeRemote(git(root,['config','--get','remote.origin.url']));return{id:crypto.createHash('sha256').update(`${root}\n${remote||''}`).digest('hex').slice(0,24),root,remote};}
function isDockyard(w){const p=readJson(path.join(w,'package.json'),{}),name=String(p?.name||'').toLowerCase(),repo=String(p?.repository?.url||'').toLowerCase();if(name==='dockyardos'||repo.includes('/dockyardos'))return true;const f=path.join(w,'integrations','antigravity','plugin','plugin.json');return fs.existsSync(f)&&String(readJson(f,{})?.name||'').toLowerCase()==='dockyardos';}
function ctx(input){const w=input.workspacePaths?.[0];if(!w)return null;const id=identity(w);const marker=readJson(path.join(w,'.agents','cortex','workspace.json'),null);if(!marker||marker.owner!=='cortex'||marker.projectId!==id.id||marker.mode!=='primary'||isDockyard(w))return null;const home=process.env.CORTEX_STATE_HOME||path.join(os.homedir(),'.antigravity-cortex');const dir=ensureDir(path.join(home,'projects',id.id));return{w,id,marker,dir};}
function snapshot(c){const status=git(c.w,['status','--porcelain=v1']);const head=git(c.w,['rev-parse','HEAD'])||null,branch=git(c.w,['branch','--show-current'])||null;return{capturedAt:new Date().toISOString(),projectId:c.id.id,projectRoot:c.id.root,remote:c.id.remote,git:{branch,head,status,changed:status.split(/\r?\n/).filter(Boolean),fingerprint:crypto.createHash('sha256').update(JSON.stringify({head,branch,status})).digest('hex')}};}
function appendEvent(c,event,payload={}){const dir=ensureDir(path.join(c.dir,'events'));const rec={at:new Date().toISOString(),event,...payload};atomicJson(path.join(dir,`${Date.now()}-${process.pid}-${Math.random().toString(16).slice(2,7)}.json`),rec);return rec;}
function maybeCheckpoint(c,reason,extra={},force=false){const latestFile=path.join(c.dir,'latest-checkpoint.json');const latest=readJson(latestFile,null),now=Date.now();if(!force&&latest?.capturedAt&&now-Date.parse(latest.capturedAt)<30000)return null;const cp={schema:2,...snapshot(c),reason,extra};const dir=ensureDir(path.join(c.dir,'checkpoints'));const file=path.join(dir,`${cp.capturedAt.replace(/[:.]/g,'-')}-${reason}.json`);atomicJson(file,cp);atomicJson(latestFile,cp);let names=fs.readdirSync(dir).filter(n=>n.endsWith('.json')).sort();while(names.length>200){try{fs.rmSync(path.join(dir,names.shift()),{force:true});}catch{break;}}return cp;}
function runtime(c){return readJson(path.join(c.dir,'runtime.json'),{schema:1,verificationEvidence:{},needsVerification:false});}
function saveRuntime(c,r){atomicJson(path.join(c.dir,'runtime.json'),r);}
function commandLine(input){const a=input.toolCall?.args||{};return String(a.CommandLine||a.command||a.Command||'');}
function targetPath(input){const a=input.toolCall?.args||{};return String(a.TargetFile||a.path||a.filePath||'');}
function verificationCategory(cmd){if(/\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?(?:test|check)\b|\bpytest\b|\bcargo\s+test\b|\bgo\s+test\b|\bgradlew(?:\.bat)?\s+test\b/i.test(cmd))return'test';if(/\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?build\b|\bcargo\s+build\b|\bgradlew(?:\.bat)?\s+(?:assemble|build)\b/i.test(cmd))return'build';if(/\b(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?(?:lint|typecheck)\b|\beslint\b|\btsc\b/i.test(cmd))return'lint';if(/playwright-cli|playwright\s+test|browser_/i.test(cmd))return'browser';if(/gitleaks|osv-scanner|\bstrix\b/i.test(cmd))return'security';return null;}
function isCodeLike(file){return /\.(?:js|jsx|ts|tsx|py|go|rs|java|kt|kts|cs|cpp|c|h|hpp|swift|dart|vue|svelte|html|css|scss|json|ya?ml|toml|gradle)$/i.test(file||'');}
function compactResume(c){const snap=snapshot(c),cp=readJson(path.join(c.dir,'latest-checkpoint.json'),null),r=runtime(c),vr=readJson(path.join(c.dir,'verification','latest.json'),null),sr=readJson(path.join(c.dir,'security','latest.json'),null);const changed=snap.git.changed.slice(0,20).join('\n')||'(clean)';let next='Inspect current state and continue from the first unfinished action.';if(vr?.status==='fail')next='Repair failed deterministic verification before new work.';else if(snap.git.changed.length)next='Inspect the existing changes before writing more code; do not redo work blindly.';else if(cp?.extra?.nextAction)next=cp.extra.nextAction;return `CORTEX ACTIVE — project ${c.id.id}. Cortex is the primary orchestrator for this workspace; never modify DockyardOS/GameFoundry orchestration paths.\nBranch: ${snap.git.branch||'(detached)'}  HEAD: ${snap.git.head||'none'}\nCheckpoint: ${cp?.capturedAt||'none'} (${cp?.reason||'none'})\nChanged files:\n${changed}\nLatest verification: ${vr?.status||'none'}; security: ${sr?.status||'none'}; verification needed: ${r.needsVerification?'yes':'no'}.\nNext action: ${next}\nWorkflow: restore -> inspect -> research if needed -> plan -> selective skills -> implement -> verify -> browser/runtime check when relevant -> security -> checkpoint. Treat repository state as authoritative over old chat memory.`.slice(0,6000);}
(async()=>{const input=await readStdin(),c=ctx(input);if(!c){if(mode==='stop')return output({decision:'stop'});return output({});}
 if(mode==='pre-invocation'){return output({injectSteps:[{ephemeralMessage:compactResume(c)}]});}
 if(mode==='post-tool'){
   const tool=String(input.toolCall?.name||''),err=String(input.error||'');const cmd=commandLine(input),target=targetPath(input);const r=runtime(c),now=new Date().toISOString();
   if(['write_to_file','replace_file_content','multi_replace_file_content'].includes(tool)){r.lastModificationAt=now;r.lastModificationPath=target||null;r.needsVerification=r.needsVerification||isCodeLike(target);r.modificationFingerprint=snapshot(c).git.fingerprint;}
   const cat=verificationCategory(cmd);if(cat&&!err){r.verificationEvidence=r.verificationEvidence||{};r.verificationEvidence[cat]=now;r.lastVerificationAt=now;if(['test','build','lint'].includes(cat))r.needsVerification=false;}
   if(err)r.lastError={at:now,tool,message:err.slice(0,1200)};
   saveRuntime(c,r);appendEvent(c,'post-tool',{tool,command:cmd.slice(0,500)||undefined,target:target||undefined,error:err||undefined,verificationCategory:cat||undefined,modelName:input.modelName,conversationId:input.conversationId});
   if(err||cat||['write_to_file','replace_file_content','multi_replace_file_content'].includes(tool))maybeCheckpoint(c,err?'tool-error':cat?`verified-${cat}`:'file-change',{tool,target,verificationCategory:cat},false);
   return output({});
 }
 if(mode==='stop'){
   const r=runtime(c),snap=snapshot(c);maybeCheckpoint(c,'agent-stop',{terminationReason:input.terminationReason,error:input.error||null},true);appendEvent(c,'stop',{terminationReason:input.terminationReason,error:input.error||undefined,fullyIdle:input.fullyIdle,conversationId:input.conversationId});
   if(input.terminationReason==='model_stop'&&input.fullyIdle===true&&r.needsVerification&&r.lastNudgeFingerprint!==snap.git.fingerprint){r.lastNudgeFingerprint=snap.git.fingerprint;saveRuntime(c,r);return output({decision:'continue',reason:'Cortex completion gate: source/config changes were made after the last adequate verification. Inspect the actual changed files, run the relevant deterministic tests/build/lint and browser/runtime check if this is UI work, repair failures, then checkpoint before claiming completion.'});}
   return output({decision:'stop'});
 }
 output({});
})().catch(()=>{if(mode==='stop')output({decision:'stop'});else output({});});
