'use strict';
const fs=require('fs');const path=require('path');const os=require('os');const childProcess=require('child_process');const crypto=require('crypto');
function die(m){process.stderr.write(`${m}\n`);process.exit(1);}function ensureDir(d){fs.mkdirSync(d,{recursive:true});return d;}function run(cmd,args,cwd){return childProcess.spawnSync(cmd,args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],shell:false,timeout:180000,maxBuffer:2*1024*1024});}
let COPY_MAX_FILES=1000,COPY_MAX_BYTES=25*1024*1024;function copy(src,dst,state={files:0,bytes:0}){ensureDir(dst);for(const e of fs.readdirSync(src,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(['.git','node_modules','.venv','venv','dist','build'].includes(e.name))continue;const s=path.join(src,e.name),d=path.join(dst,e.name);if(e.isSymbolicLink())throw new Error(`Symlink rejected: ${s}`);if(e.isDirectory())copy(s,d,state);else if(e.isFile()){const z=fs.statSync(s).size;state.files++;state.bytes+=z;if(state.files>COPY_MAX_FILES||state.bytes>COPY_MAX_BYTES)throw new Error('Skill exceeds safety limits');fs.copyFileSync(s,d);}}return state;}
function ns(id){return`cortex-${id.toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'')}`;}function rewrite(md,name,desc){let t=String(md);if(t.startsWith('---\n')){const e=t.indexOf('\n---',4);if(e>0){let fm=t.slice(4,e);fm=/^name\s*:/m.test(fm)?fm.replace(/^name\s*:.*$/m,`name: ${name}`):`name: ${name}\n${fm}`;if(desc&&!/^description\s*:/m.test(fm))fm+=`\ndescription: ${desc}`;return`---\n${fm}\n---${t.slice(e+4)}`;}}return`---\nname: ${name}\ndescription: ${desc||'Cortex trusted skill'}\n---\n\n${t}`;}
const args=process.argv.slice(2),scopeArg=args.find(x=>x.startsWith('--scope=')),scope=scopeArg?scopeArg.split('=')[1]:'ide-global',ids=args.filter(x=>!x.startsWith('--'));if(!ids.length)die('Usage: node skill-ensure.js <skill-id> [...] [--scope=ide-global|cli-global|both]');
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'..','catalog','skills.json'),'utf8')),map=new Map(catalog.skills.map(x=>[x.id,x]));const stateHome=process.env.CORTEX_STATE_HOME||path.join(os.homedir(),'.antigravity-cortex'),cache=ensureDir(path.join(stateHome,'cache','repos'));const bases=scope==='both'?[path.join(os.homedir(),'.gemini','config','skills'),path.join(os.homedir(),'.gemini','antigravity-cli','skills')]:[scope==='cli-global'?path.join(os.homedir(),'.gemini','antigravity-cli','skills'):path.join(os.homedir(),'.gemini','config','skills')];
const results=[];for(const id of ids){const e=map.get(id);if(!e||e.trusted!==true){results.push({id,status:'rejected',error:'not allow-listed'});continue;}try{COPY_MAX_FILES=Number(e.maxFiles||1000);COPY_MAX_BYTES=Number(e.maxBytes||25*1024*1024);const dest=path.join(cache,id);if(!fs.existsSync(path.join(dest,'.git'))){fs.rmSync(dest,{recursive:true,force:true});let r=run('git',['clone','--depth','1','--branch',e.ref||'main',e.repo,dest]);if(r.status!==0)throw new Error((r.stderr||'clone failed').slice(-600));}else{let r=run('git',['fetch','--depth','1','origin',e.ref||'main'],dest);if(r.status!==0)throw new Error((r.stderr||'fetch failed').slice(-600));r=run('git',['reset','--hard','FETCH_HEAD'],dest);if(r.status!==0)throw new Error('reset failed');}const sha=(run('git',['rev-parse','HEAD'],dest).stdout||'').trim(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'cortex-skill-')),source=e.skillDir?path.join(dest,e.skillDir):dest;if(e.sourceFile){fs.writeFileSync(path.join(tmp,'SKILL.md'),fs.readFileSync(path.join(dest,e.sourceFile),'utf8'));}else{if(!fs.existsSync(path.join(source,'SKILL.md')))throw new Error('SKILL.md missing at trusted source path');copy(source,tmp);}const skillName=ns(e.installName||id);fs.writeFileSync(path.join(tmp,'SKILL.md'),rewrite(fs.readFileSync(path.join(tmp,'SKILL.md'),'utf8'),skillName,e.description));const installed=[];for(const b of bases){ensureDir(b);const t=path.join(b,skillName),stage=`${t}.stage-${process.pid}`;fs.rmSync(stage,{recursive:true,force:true});copy(tmp,stage);fs.writeFileSync(path.join(stage,'.cortex-source.json'),JSON.stringify({id,repo:e.repo,commit:sha,license:e.license||null,installedAt:new Date().toISOString()},null,2));fs.rmSync(t,{recursive:true,force:true});fs.renameSync(stage,t);installed.push(t);}fs.rmSync(tmp,{recursive:true,force:true});results.push({id,status:'installed',commit:sha,paths:installed});}catch(err){results.push({id,status:'failed',error:err.message});}}
process.stdout.write(`${JSON.stringify({scope,results},null,2)}\n`);process.exit(results.some(x=>x.status==='failed')?2:0);
