'use strict';
const fs=require('fs');const path=require('path');const cp=require('child_process');const os=require('os');
const root=path.resolve(__dirname,'..');let failures=[];const pass=[];
function check(cond,msg){if(cond)pass.push(msg);else failures.push(msg);}function json(rel){return JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'));}
const pkg=json('package.json'),plugin=json('antigravity-plugin/cortex/plugin.json'),hooks=json('antigravity-plugin/cortex/hooks.json'),catalog=json('antigravity-plugin/cortex/catalog/skills.json'),mcp=json('antigravity-plugin/cortex/mcp_config.json');
check(pkg.name==='antigravity-cortex','package identity');check(pkg.publisher==='cassiel','publisher');check(plugin.name==='cortex','plugin namespace');check(Boolean(hooks['cortex-context']?.PreInvocation),'PreInvocation context hook');check(Boolean(hooks['cortex-completion-gate']?.Stop),'Stop completion gate');check(mcp.mcpServers?.['cortex-inspo']?.disabled===true,'Inspo MCP disabled by default');check(new Set(catalog.skills.map(x=>x.id)).size===catalog.skills.length,'skill catalog IDs unique');check(catalog.skills.every(x=>x.trusted===true&&/^https:\/\/github\.com\//.test(x.repo)),'skill catalog allow-listed GitHub HTTPS sources');
const skillRoot=path.join(root,'antigravity-plugin','cortex','skills');const skillDirs=fs.readdirSync(skillRoot,{withFileTypes:true}).filter(x=>x.isDirectory());for(const d of skillDirs){const f=path.join(skillRoot,d.name,'SKILL.md');check(fs.existsSync(f),`skill ${d.name}`);if(fs.existsSync(f))check(/^---\n[\s\S]*?\n---/m.test(fs.readFileSync(f,'utf8')),`skill frontmatter ${d.name}`);}
const scripts=['extension.js',...fs.readdirSync(path.join(root,'src')).filter(x=>x.endsWith('.js')).map(x=>`src/${x}`),...fs.readdirSync(path.join(root,'antigravity-plugin','cortex','scripts')).filter(x=>x.endsWith('.js')).map(x=>`antigravity-plugin/cortex/scripts/${x}`)];for(const rel of scripts){const r=cp.spawnSync(process.execPath,['--check',path.join(root,rel)],{encoding:'utf8'});check(r.status===0,`syntax ${rel}${r.status===0?'':`: ${r.stderr}`}`);}
const t=cp.spawnSync(process.execPath,['--test','test/*.test.js'],{cwd:root,encoding:'utf8',shell:true,timeout:120000,maxBuffer:4*1024*1024});check(t.status===0,`test suite${t.status===0?'':`: ${t.stdout}\n${t.stderr}`}`);
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'cortex-cleanroom-'));try{fs.cpSync(root,temp,{recursive:true,filter:(src)=>!src.includes(`${path.sep}releases${path.sep}`)&&!src.endsWith('.vsix')&&!src.endsWith('.zip')});const r=cp.spawnSync(process.execPath,['--check',path.join(temp,'extension.js')],{encoding:'utf8'});check(r.status===0,'clean-room extension syntax');}finally{fs.rmSync(temp,{recursive:true,force:true});}
console.log(`Cortex verification: ${failures.length?'FAIL':'PASS'}`);for(const p of pass)console.log(`  PASS ${p}`);for(const f of failures)console.error(`  FAIL ${f}`);if(failures.length)process.exit(1);
