'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');const childProcess=require('child_process');const {workspaceStateDir,canExecute}=require('./isolation');const {ensureDir,readJson,atomicWriteJson,trimFiles}=require('./fs-safe');const {gitValue}=require('./project-id');
function projectPaths(workspace){const {identity,dir}=workspaceStateDir(workspace);return{identity,dir,checkpoints:ensureDir(path.join(dir,'checkpoints')),events:ensureDir(path.join(dir,'events')),verification:ensureDir(path.join(dir,'verification')),security:ensureDir(path.join(dir,'security')),memory:ensureDir(path.join(dir,'memory'))};}
function gitRaw(workspace,args){try{return childProcess.execFileSync('git',['-C',workspace,...args],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).replace(/\r?\n$/,'');}catch{return '';}}
function parseStatus(text){return String(text||'').split(/\r?\n/).filter(Boolean).map(line=>({code:line.slice(0,2),file:line.slice(3).trim()}));}
function snapshot(workspace){const {identity}=projectPaths(workspace);const status=gitRaw(workspace,['status','--porcelain=v1']);const head=gitValue(workspace,['rev-parse','HEAD'])||null;const branch=gitValue(workspace,['branch','--show-current'])||null;const recent=gitValue(workspace,['log','-8','--pretty=%H%x09%aI%x09%s']);const staged=gitRaw(workspace,['diff','--cached','--name-status']);const unstaged=gitRaw(workspace,['diff','--name-status']);const changed=parseStatus(status);const fingerprint=crypto.createHash('sha256').update(JSON.stringify({head,branch,status,staged,unstaged})).digest('hex');return{schema:2,projectId:identity.id,projectRoot:identity.root,remote:identity.remote,capturedAt:new Date().toISOString(),git:{branch,head,status,recent,staged,unstaged,changed,fingerprint}};}
function createCheckpoint(workspace,reason='manual',extra={},options={}){const access=canExecute(workspace);if(!access.ok)throw new Error(`Checkpoint refused: ${access.reason}`);const p=projectPaths(workspace);const cp={...snapshot(workspace),reason,extra};const stamp=cp.capturedAt.replace(/[:.]/g,'-');const file=path.join(p.checkpoints,`${stamp}-${String(reason).replace(/[^a-z0-9-]+/gi,'-').slice(0,32)}.json`);atomicWriteJson(file,cp);atomicWriteJson(path.join(p.dir,'latest-checkpoint.json'),cp);trimFiles(p.checkpoints,Number(options.maxHistory||200));return{file,checkpoint:cp};}
function latestCheckpoint(workspace){return readJson(path.join(projectPaths(workspace).dir,'latest-checkpoint.json'),null);}
function appendEvent(workspace,event,payload={}){const p=projectPaths(workspace);const rec={schema:1,at:new Date().toISOString(),event,...payload};const file=path.join(p.events,`${Date.now()}-${process.pid}-${Math.random().toString(16).slice(2,8)}.json`);atomicWriteJson(file,rec);trimFiles(p.events,1000);return rec;}
function readRecentEvents(workspace,limit=40){const p=projectPaths(workspace);let names=[];try{names=fs.readdirSync(p.events).filter(n=>n.endsWith('.json')).sort().slice(-limit);}catch{return [];}return names.map(n=>readJson(path.join(p.events,n),null)).filter(Boolean);}
function recordMemory(workspace,kind,value){const p=projectPaths(workspace);const file=path.join(p.memory,`${kind}.jsonl`);fs.appendFileSync(file,`${JSON.stringify({at:new Date().toISOString(),...value})}\n`,{mode:0o600});return file;}
function reconcile(workspace){const previous=latestCheckpoint(workspace),current=snapshot(workspace);if(!previous)return{previous:null,current,stale:true,reasons:['no-checkpoint']};const reasons=[];if(previous.git?.head!==current.git.head)reasons.push('git-head-changed');if(previous.git?.fingerprint!==current.git.fingerprint)reasons.push('working-tree-changed');return{previous,current,stale:reasons.length>0,reasons};}
function latestReport(workspace,type){const p=projectPaths(workspace);return readJson(path.join(p[type],'latest.json'),null);}
module.exports={projectPaths,parseStatus,snapshot,createCheckpoint,latestCheckpoint,appendEvent,readRecentEvents,recordMemory,reconcile,latestReport};
