'use strict';
const fs=require('fs');const path=require('path');const {workspaceStateDir,canExecute}=require('./isolation');const {ensureDir,atomicWriteJson,readJson}=require('./fs-safe');const {gitValue}=require('./project-id');const {commandExists,run}=require('./process');
const PATTERNS=[
 {id:'private-key',severity:'critical',re:/-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/},
 {id:'github-token',severity:'critical',re:/\b(?:ghp_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{30,})\b/},
 {id:'aws-access-key',severity:'high',re:/\bAKIA[0-9A-Z]{16}\b/},
 {id:'slack-token',severity:'high',re:/\bxox[baprs]-[A-Za-z0-9-]{20,}\b/}
];
function trackedFiles(workspace){const out=gitValue(workspace,['ls-files','-co','--exclude-standard']);return out.split(/\r?\n/).filter(Boolean);}
function looksBinary(buf){const n=Math.min(buf.length,4096);for(let i=0;i<n;i++)if(buf[i]===0)return true;return false;}
function scanSecrets(workspace){const findings=[];for(const rel of trackedFiles(workspace)){if(/(^|\/)(\.git|node_modules|dist|build|\.next|coverage)(\/|$)/.test(rel.replace(/\\/g,'/')))continue;const f=path.join(workspace,rel);let st;try{st=fs.statSync(f);}catch{continue;}if(!st.isFile()||st.size>2*1024*1024)continue;let buf;try{buf=fs.readFileSync(f);}catch{continue;}if(looksBinary(buf))continue;const text=buf.toString('utf8');for(const p of PATTERNS){const m=p.re.exec(text);if(m){const before=text.slice(0,m.index);const line=before.split(/\r?\n/).length;findings.push({id:p.id,severity:p.severity,file:rel,line,redacted:true});}}}return findings;}
async function runExternal(workspace,allowed){const checks=[];if(!allowed)return checks;for(const item of [{id:'gitleaks',cmd:'gitleaks',args:['detect','--no-banner','--redact','--source','.']},{id:'osv-scanner',cmd:'osv-scanner',args:['scan','source','-r','.']}]){const ex=await commandExists(item.cmd);if(!ex.ok){checks.push({id:item.id,status:'unavailable'});continue;}const r=await run(item.cmd,item.args,{cwd:workspace,timeoutMs:8*60*1000,maxOutput:200000});checks.push({id:item.id,status:r.code===0?'pass':'fail',code:r.code,output:(r.stdout+r.stderr).slice(-12000)});}return checks;}
async function runSecurityAudit(workspace,{allowExternal=false}={}){const access=canExecute(workspace);if(!access.ok)throw new Error(`Security audit refused: ${access.reason}`);const findings=scanSecrets(workspace);const checks=await runExternal(workspace,allowExternal);const config=readJson(path.join(workspace,'.agents','cortex','security.json'),{});let strix={status:'not-configured'};if(config?.strix?.enabled===true&&config?.strix?.authorized===true&&allowExternal){const ex=await commandExists('strix');if(ex.ok){const args=Array.isArray(config.strix.args)?config.strix.args:[];const r=await run('strix',args,{cwd:workspace,timeoutMs:15*60*1000,maxOutput:200000});strix={status:r.code===0?'pass':'fail',code:r.code,output:(r.stdout+r.stderr).slice(-12000)};}else strix={status:'unavailable'};}
const critical=findings.filter(x=>x.severity==='critical'||x.severity==='high');const report={schema:1,at:new Date().toISOString(),owaspPolicy:'bundled-cortex-security-gate',secretScan:{status:critical.length?'fail':'pass',findings},externalChecks:checks,strix,status:critical.length||checks.some(x=>x.status==='fail')||strix.status==='fail'?'fail':'pass'};const dir=ensureDir(path.join(workspaceStateDir(workspace).dir,'security'));atomicWriteJson(path.join(dir,`${Date.now()}.json`),report);atomicWriteJson(path.join(dir,'latest.json'),report);return report;}
module.exports={PATTERNS,trackedFiles,scanSecrets,runSecurityAudit};
