'use strict';
const fs=require('fs');const path=require('path');const {canExecute,workspaceStateDir}=require('./isolation');const {run,commandExists}=require('./process');const {atomicWriteJson,ensureDir}=require('./fs-safe');
function packageManager(workspace){if(fs.existsSync(path.join(workspace,'pnpm-lock.yaml')))return'pnpm';if(fs.existsSync(path.join(workspace,'yarn.lock')))return'yarn';if(fs.existsSync(path.join(workspace,'bun.lockb'))||fs.existsSync(path.join(workspace,'bun.lock')))return'bun';return'npm';}
function nodeScriptCommand(pm,script){if(pm==='yarn')return{cmd:'yarn',args:[script]};if(pm==='bun')return{cmd:'bun',args:['run',script]};return{cmd:pm,args:['run',script]};}
function verificationPlan(workspace){const steps=[];const pkgFile=path.join(workspace,'package.json');if(fs.existsSync(pkgFile)){let pkg={};try{pkg=JSON.parse(fs.readFileSync(pkgFile,'utf8'));}catch{}const scripts=pkg.scripts||{},pm=packageManager(workspace);if(scripts.check){steps.push({id:'node-check',...nodeScriptCommand(pm,'check')});if(scripts.build)steps.push({id:'node-build',...nodeScriptCommand(pm,'build')});}else{for(const s of ['lint','typecheck','test','build'])if(scripts[s])steps.push({id:`node-${s}`,...nodeScriptCommand(pm,s)});}}
if(fs.existsSync(path.join(workspace,'pyproject.toml'))||fs.existsSync(path.join(workspace,'pytest.ini')))steps.push({id:'pytest',cmd:'pytest',args:['-q']});
if(fs.existsSync(path.join(workspace,'go.mod')))steps.push({id:'go-test',cmd:'go',args:['test','./...']});
if(fs.existsSync(path.join(workspace,'Cargo.toml')))steps.push({id:'cargo-test',cmd:'cargo',args:['test','--all-targets']});
if(fs.existsSync(path.join(workspace,'gradlew'))||fs.existsSync(path.join(workspace,'gradlew.bat')))steps.push({id:'gradle-test',cmd:process.platform==='win32'?'gradlew.bat':'./gradlew',args:['test']});
return steps;}
async function runVerification(workspace,{timeoutMs=12*60*1000}={}){const access=canExecute(workspace);if(!access.ok)throw new Error(`Verification refused: ${access.reason}`);const steps=verificationPlan(workspace);const results=[];for(const s of steps){const available=s.cmd.startsWith('./')||fs.existsSync(path.join(workspace,s.cmd))?{ok:true}:await commandExists(s.cmd);if(!available.ok){results.push({...s,status:'unavailable',code:null});continue;}const startedAt=new Date().toISOString();const r=await run(s.cmd,s.args,{cwd:workspace,timeoutMs,maxOutput:250000});results.push({...s,startedAt,finishedAt:new Date().toISOString(),status:r.code===0?'pass':'fail',code:r.code,stdout:r.stdout.slice(-12000),stderr:r.stderr.slice(-12000),timedOut:r.timedOut});if(r.code!==0)break;}const report={schema:1,at:new Date().toISOString(),steps,results,status:steps.length===0?'no-tests':results.some(x=>x.status==='fail')?'fail':results.every(x=>x.status==='pass')?'pass':'partial'};const dir=ensureDir(path.join(workspaceStateDir(workspace).dir,'verification'));atomicWriteJson(path.join(dir,`${Date.now()}.json`),report);atomicWriteJson(path.join(dir,'latest.json'),report);return report;}
module.exports={packageManager,nodeScriptCommand,verificationPlan,runVerification};
